apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_DATABASE: taskmanager
  DB_URL: jdbc:mysql://database:3306/taskmanager?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC