apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_USER: d2FyZWhvdXNlX3VzZXI=   # Base64 of warehouse_user
  MONGO_PASSWORD: d2FyZWhvdXNlX3Bhc3M= # Base64 of warehouse_pass
